config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @new_task = Task.new
  end

  def create
    @new_task = Task.create(task_params)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def delete
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Hello here you will edit your task</h1>


<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.check_box :completed %>
    <%= f.label :completed, class: 'form-control' %>

  </div>
  <%= f.submit class: 'btn btn-primary' %>
<%end%>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @tasks.each do |task|%>
    <li><%= check_box("li", task['id'], {checked: task['completed'] == true}) %>
      <%= link_to task['title'], task_path(task['id']) %></li>
    <li><%= link_to "Delete", task_path(task['id']),
      method: :delete,
      data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>

<div class="add">
  <%= link_to "Add a new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<h1>New task !</h1>


<div class="content">

  <%= form_for(@new_task) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :completed %>
      <%= f.text_field :completed, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary'  %>
  <% end %>

  <%= link_to "Back to list", tasks_path %>

</div>

app/views/tasks/show.html.erb
<button type="button" class="edit-btn"><%= link_to "Edit Task", edit_path(@task) %></button>

<h1><%= @task['title'] %></h1>

<div class="content border-bottom-0" >
  <p class="details"><%= @task['details'] %></p>

  <p><%= check_box("p", @task['id'], {checked: @task['completed'] == true}) %>
  This task is completed</p>
   <%= link_to "Back to list", tasks_path %>
</div>